<!doctype html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page { margin: 130px 45px 70px 45px; }
    * { font-family: 'DejaVu Sans', sans-serif; }
    body { color: #0F172A; font-size: 11px; line-height: 1.5; }
    header { position: fixed; top: -95px; left: 0; right: 0; height: 80px; }
    .brandbar { height: 6px; background: #7C3AED; border-radius: 3px; }
    .brand { margin-top: 12px; font-size: 18px; font-weight: bold; color: #5B21B6; }
    .brand small { color: #64748B; font-weight: normal; font-size: 10px; }
    footer { position: fixed; bottom: -50px; left: 0; right: 0; height: 40px; color: #64748B; font-size: 9px; border-top: 1px solid #E2E8F0; padding-top: 6px; }
    h1 { font-size: 20px; color: #0F172A; margin: 0 0 4px; }
    .meta { color: #64748B; margin-bottom: 18px; }
    .meta-grid td { padding: 3px 12px 3px 0; color: #0F172A; }
    .meta-grid .label { color: #64748B; width: 90px; }
    h2 { font-size: 13px; color: #5B21B6; margin: 20px 0 8px; padding-bottom: 4px; border-bottom: 1px solid #E2E8F0; }
    ul { margin: 0 0 10px; padding-left: 18px; }
    li { margin-bottom: 4px; }
    .decision, .action { background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 8px; padding: 8px 10px; margin-bottom: 6px; }
    .action .assignee { color: #2563EB; }
    .badge { display: inline-block; font-size: 8px; padding: 1px 6px; border-radius: 8px; background: #EDE9FE; color: #5B21B6; }
    .disc h3 { font-size: 11px; margin: 8px 0 3px; }
</style>
</head>
<body>
    <header>
        <div class="brandbar"></div>
        <div class="brand">MeetingAI <small>· Minutes of Meeting</small></div>
    </header>
    <footer>
        Generated by MeetingAI · {{ $mom->status === 'published' ? 'Published' : 'Draft' }}
        @if($mom->approved_at) · Approved {{ $mom->approved_at->format('d M Y') }} @endif
    </footer>

    <h1>{{ $mom->title }}</h1>
    <table class="meta-grid">
        <tr>
            <td class="label">Date</td><td>{{ optional($meeting->scheduled_start_at)->format('d M Y') }}</td>
            <td class="label">Time</td><td>{{ optional($meeting->scheduled_start_at)->format('H:i') }}–{{ optional($meeting->scheduled_end_at)->format('H:i') }}</td>
        </tr>
        <tr>
            <td class="label">Organizer</td><td>{{ $meeting->organizer?->name ?? '—' }}</td>
            <td class="label">Platform</td><td>Google Meet</td>
        </tr>
    </table>

    @php $s = $sections; @endphp

    @if(!empty($s['objective']))
        <h2>Objective</h2>
        <p>{{ $s['objective'] }}</p>
    @endif

    @if(!empty($s['executive_summary']))
        <h2>Executive Summary</h2>
        <ul>@foreach($s['executive_summary'] as $p)<li>{{ $p }}</li>@endforeach</ul>
    @endif

    @if(!empty($s['detailed_discussions']))
        <h2>Detailed Discussions</h2>
        <div class="disc">
        @foreach($s['detailed_discussions'] as $d)
            <h3>{{ $d['heading'] ?? '' }}</h3>
            <ul>@foreach($d['points'] ?? [] as $pt)<li>{{ $pt }}</li>@endforeach</ul>
        @endforeach
        </div>
    @endif

    @if(!empty($s['decisions']))
        <h2>Decisions</h2>
        @foreach($s['decisions'] as $d)
            <div class="decision">
                @if(!empty($d['topic']))<span class="badge">{{ $d['topic'] }}</span> @endif
                {{ $d['decision'] ?? '' }}
            </div>
        @endforeach
    @endif

    @if(!empty($s['action_items']))
        <h2>Action Items</h2>
        @foreach($s['action_items'] as $a)
            <div class="action">
                {{ $a['title'] ?? '' }}
                @if(!empty($a['assignee_name_raw']))<span class="assignee">— {{ $a['assignee_name_raw'] }}</span>@endif
                @if(!empty($a['due_date']))<span> · due {{ $a['due_date'] }}</span>@endif
            </div>
        @endforeach
    @endif

    @if(!empty($s['risks']))
        <h2>Risks</h2>
        <ul>@foreach($s['risks'] as $r)<li>{{ $r['title'] ?? '' }}</li>@endforeach</ul>
    @endif

    @if(!empty($s['open_questions']))
        <h2>Open Questions</h2>
        <ul>@foreach($s['open_questions'] as $q)<li>{{ $q['question'] ?? '' }}</li>@endforeach</ul>
    @endif

    @if(!empty($s['next_steps']))
        <h2>Next Steps</h2>
        <ul>@foreach($s['next_steps'] as $n)<li>{{ $n }}</li>@endforeach</ul>
    @endif
</body>
</html>
